INSERT INTO restaurants (name, location, location_type, disney_url, price_range, cuisine, requires_reservation, accepts_walk_ins, is_active) VALUES
('eet by Maneet Chauhan', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/eet-by-maneet-chauhan/', '$$', 'Indian', true, false, true),
('Jaleo by José Andrés', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/jaleo/', '$$', 'Seafood, Spanish', true, false, true),
('Tiffins Restaurant', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/tiffins/', '$$$', 'African, Asian, Latin', true, false, true),
('Toledo - Tapas, Steak & Seafood', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/toledo/', '$$$', 'Seafood, Spanish, Steakhouse', true, false, true),
('4 Rivers Cantina Barbacoa Food Truck', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/4-rivers-cantina-food-truck/', '$', 'Latin, Mexican', false, true, true),
('ABC Commissary', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/abc-commissary/', '$', 'American', false, true, true),
('AbracadaBar', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/abracadabar/', '$$', 'American', false, false, true),
('Ale & Compass Lounge', 'Disney''s Yacht Club Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/yacht-club-resort/ale-and-compass-lounge/', '$$', 'American', false, false, true),
('Ale & Compass Restaurant', 'Disney''s Yacht Club Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/yacht-club-resort/ale-and-compass/', '$$', 'American', true, false, true),
('Aloha Isle', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/aloha-isle/', '$', 'American', false, true, true),
('Amare', 'Walt Disney World Swan Reserve', 'Resort', 'https://disneyworld.disney.go.com/dining/swan-reserve/amare/', '$$$', 'Mediterranean', true, false, true),
('AMC Disney Springs 24 Dine-In Theatres', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/fork-and-screen-dine-in-theatre/', '$', 'American, Seafood', false, false, true),
('Amorette''s Patisserie', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/amorettes-patisserie/', '$', 'Bakery', false, true, true),
('Anaheim Produce', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/anaheim-produce/', '$', 'American', false, true, true),
('Anandapur Ice Cream Truck', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/anandapur-ice-cream-truck/', '$', 'American', false, true, true),
('Arctic Expeditions', 'Blizzard Beach', 'Park', 'https://disneyworld.disney.go.com/dining/blizzard-beach/arctic-expeditions/', '$', 'American', false, true, true),
('The Artist''s Palette', 'Disney''s Saratoga Springs Resort & Spa', 'Resort', 'https://disneyworld.disney.go.com/dining/saratoga-springs-resort-and-spa/artists-palette/', '$', 'American', false, true, true),
('Astrofizz', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/astrofizz/', '$', 'American', false, true, true),
('Auntie Gravity''s Galactic Goodies', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/auntie-gravitys-galactic-goodies/', '$', 'American', false, true, true),
('Avalunch', 'Blizzard Beach', 'Park', 'https://disneyworld.disney.go.com/dining/blizzard-beach/avalunch/', '$', 'American', false, true, true),
('B.B. Wolf''s Sausage Co.', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/bb-wolfs-sausage-co/', '$', 'American', false, true, true),
('Backlot Express', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/backlot-express/', '$', 'American', false, true, true),
('Backstretch Pool Bar', 'Disney''s Saratoga Springs Resort & Spa', 'Resort', 'https://disneyworld.disney.go.com/dining/saratoga-springs-resort-and-spa/backstretch-pool-bar/', '$', 'American', false, true, true),
('Banana Cabana', 'Disney''s Caribbean Beach Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/caribbean-beach-resort/banana-cabana-pool-bar/', '$$', 'American', false, false, true),
('Bar Riva', 'Disney''s Riviera Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/riviera-resort/bar-riva/', '$', '', false, false, true),
('Barcelona Lounge', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/barcelona-lounge/', '$', 'American', false, false, true),
('Barefoot Pool Bar', 'Disney''s Polynesian Village Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/polynesian-resort/barefoot-pool-bar/', '$', 'American', false, true, true),
('BaseLine Tap House', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/baseline-tap-house/', '$', 'American', false, false, true),
('The Basket at Wine Bar George', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/the-basket/', '$', '', false, true, true),
('Beach Club Marketplace', 'Disney''s Beach Club Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/beach-club-resort/beach-club-marketplace/', '$', 'American', false, true, true),
('Beaches Pool Bar & Grill', 'Disney''s Grand Floridian Resort & Spa', 'Resort', 'https://disneyworld.disney.go.com/dining/grand-floridian-resort-and-spa/beach-pool-bar/', '$', 'American', false, true, true),
('The Beak and Barrel', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/beak-barrel/', '$$', 'American', true, false, true),
('Belle Vue Lounge', 'Disney''s BoardWalk Inn', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk-inn/belle-vue-lounge/', '$', 'American', false, false, true),
('Blaze Fast-Fire''d Pizza', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/blaze-pizza/', '$', 'American', false, true, true),
('Block & Hans', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/block-hans/', '$', 'American', false, false, true),
('Blue Ribbon Corn Dogs', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/blue-ribbon-corn-dog/', '$', 'American', false, true, true),
('BoardWalk Deli', 'Disney''s BoardWalk Inn', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/boardwalk-deli/', '$', 'American', false, true, true),
('BoardWalk Ice Cream', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/boardwalk-ice-cream/', '$', '', false, true, true),
('BoardWalk Joe''s Marvelous Margaritas', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/boardwalk-joes-marvelous-margaritas/', '$', 'American', false, false, true),
('Boatwright''s Dining Hall', 'Disney''s Port Orleans Resort - Riverside', 'Resort', 'https://disneyworld.disney.go.com/dining/port-orleans-resort-riverside/boatwright-dining-hall/', '$$', 'American', true, false, true),
('Bourbon Steak - A Michael Mina Restaurant', 'Walt Disney World Dolphin Hotel', 'Resort', 'https://disneyworld.disney.go.com/dining/dolphin-hotel/bourbon-steak/', '$$$', 'American, Steakhouse', true, false, true),
('Bourbon Steak Lounge', 'Walt Disney World Dolphin Hotel', 'Resort', 'https://disneyworld.disney.go.com/dining/dolphin-hotel/bourbon-steak-lounge/', '$', 'American', false, false, true),
('Cabana Bar and Beach Club', 'Walt Disney World Dolphin Hotel', 'Resort', 'https://disneyworld.disney.go.com/dining/dolphin-hotel/cabana-bar-and-beach-club/', '$', 'American', false, false, true),
('Cafe Rix', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/cafe-rix/', '$', 'American', false, true, true),
('The Cake Bake Shop Bakery by Gwendolyn Rogers', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/cake-bake-shop-bakery/', '$$', 'American', false, true, true),
('The Cake Bake Shop Restaurant by Gwendolyn Rogers', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/cake-bake-shop-restaurant/', '$$$$', 'American', true, false, true),
('Cape Town Lounge and Wine Bar', 'Disney''s Animal Kingdom Lodge', 'Resort', 'https://disneyworld.disney.go.com/dining/animal-kingdom-lodge/cape-town-lounge-and-wine-bar/', '$', 'African', false, false, true),
('Capt. Cook''s', 'Disney''s Polynesian Village Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/polynesian-resort/capt-cooks/', '$', 'American, Polynesian', false, true, true),
('Caravan Road', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/caravan-road/', '$', 'Asian', false, true, true),
('Carousel Coffee', 'Disney''s BoardWalk Inn', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/carousel-coffee/', '$', 'American', false, true, true),
('Casey''s Corner', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/caseys-corner/', '$', 'American', false, true, true),
('Catalina Eddie''s', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/catalina-eddies/', '$', 'American', false, true, true),
('Centertown Market', 'Disney''s Caribbean Beach Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/caribbean-beach-resort/centertown-market/', '$', 'American, Caribbean, Latin', false, true, true),
('Chip & Dale''s Café', 'Disney''s Contemporary Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/contemporary-resort/chip-and-dales-cafe/', '$', 'American', false, true, true),
('Connections Café', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/connections-cafe/', '$', 'American', false, true, true),
('Connections Eatery', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/connections-eatery/', '$', 'American', false, true, true),
('Contempo Café', 'Disney''s Contemporary Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/contemporary-resort/contempo-cafe/', '$', 'American', false, true, true),
('Cool Wash', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/cool-wash/', '$', 'American', false, true, true),
('Cosmic Ray''s Starlight Café', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/cosmic-rays-starlight-cafe/', '$', 'American', false, true, true),
('Creature Comforts', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/creature-comforts/', '$', 'American', false, true, true),
('D-Luxe Burger', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/d-luxe-burger/', '$', 'American', false, true, true),
('Dawa Bar', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/dawa-bar/', '$', 'American', false, false, true),
('Dine with an Imagineer', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/dine-with-an-imagineer/', '$$$$', '', true, false, true),
('Docking Bay 7 Food and Cargo', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/docking-bay-7/', '$', 'American', false, true, true),
('Dockside Margaritas', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/dockside-margaritas/', '$', 'American', false, false, true),
('Drinkwallah', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/drinkwallah/', '$', '', false, true, true),
('Dundy''s Sundries', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/dundys-sundries/', '$', 'American', false, true, true),
('Earl of Sandwich', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/earl-of-sandwich/', '$', 'American', false, true, true),
('Eight Spoon Café', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/eight-spoon-cafe/', '$', 'American', false, true, true),
('El Mercado de Coronado', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/el-mercado-de-coronado/', '$', 'American, Latin, Mexican', false, true, true),
('Electric Umbrella', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/electric-umbrella/', '$', 'American', false, true, true),
('Enchanted Rose Lounge', 'Disney''s Grand Floridian Resort & Spa', 'Resort', 'https://disneyworld.disney.go.com/dining/grand-floridian-resort-and-spa/enchanted-rose/', '$$', 'American', false, false, true),
('ESPN Sports Club', 'Disney''s BoardWalk', 'Resort', 'https://disneyworld.disney.go.com/dining/boardwalk/espn-sports-club/', '$$', 'American', false, false, true),
('Everything POP Shopping & Dining', 'Disney''s Pop Century Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/pop-century-resort/everything-pop/', '$', 'American', false, true, true),
('Fairfax Fare', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/fairfax-fare/', '$', 'American', false, true, true),
('Flame Tree Barbecue', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/flame-tree-barbecue/', '$', 'American, Barbecue', false, true, true),
('Fife & Drum Tavern', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/fife-and-drum-tavern/', '$', 'American', false, true, true),
('Food Courts at Disney''s All-Star Movies Resort', 'Disney''s All-Star Movies Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/all-star-movies-resort/world-premiere-food-court/', '$', 'American', false, true, true),
('Food Courts at Disney''s All-Star Music Resort', 'Disney''s All-Star Music Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/all-star-music-resort/intermission-food-court/', '$', 'American', false, true, true),
('Food Courts at Disney''s All-Star Sports Resort', 'Disney''s All-Star Sports Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/all-star-sports-resort/end-zone-food-court/', '$', 'American', false, true, true),
('Fresh Mediterranean Market', 'Walt Disney World Dolphin Hotel', 'Resort', 'https://disneyworld.disney.go.com/dining/dolphin-hotel/fresh-mediterranean-market/', '$$', 'Mediterranean', false, false, true),
('Frontera Cocina', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/frontera-cocina/', '$$', 'Mexican', true, false, true),
('Funnel Cake Stand', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/funnel-cakes/', '$', 'American', false, true, true),
('Gasparilla Island Grill', 'Disney''s Grand Floridian Resort & Spa', 'Resort', 'https://disneyworld.disney.go.com/dining/grand-floridian-resort-and-spa/gasparilla-island-grill/', '$', 'American', false, true, true),
('Gaston''s Tavern', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/gastons-tavern/', '$', 'American', false, true, true),
('Gelateria Toscana', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/gelateria-toscana/', '$', 'Italian', false, true, true),
('Gideon''s Bakehouse', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/gideons-bakehouse/', '$', '', false, true, true),
('Golden Oak Outpost', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/golden-oak-outpost/', '$', 'American', false, true, true),
('Good''s Food to Go', 'Disney''s Old Key West Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/old-key-west-resort/goods-food-to-go/', '$', 'American', false, true, true),
('Gurgling Suitcase at Old Key West Resort', 'Disney''s Old Key West Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/old-key-west-resort/gurgling-suitcase/', '$', 'American', false, false, true),
('Harambe Market', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/harambe-market/', '$', 'African, American', false, true, true),
('Hurricane Hanna''s Waterside Bar and Grill', 'Disney''s Beach Club Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/yacht-club-resort/hurricane-hannas/', '$', 'American', false, true, true),
('Intermission Food Court', 'Disney''s All-Star Music Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/all-star-music-resort/singing-spirits-pool-bar/', '$', 'American', false, true, true),
('Jock Lindsey''s Hangar Bar', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/jock-lindseys-hangar-bar/', '$$', 'American', false, false, true),
('Joy of Tea', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/joy-of-tea/', '$', 'Chinese', false, true, true),
('Jungle Navigation Co. LTD Skipper Canteen', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/jungle-navigation-skipper-canteen/', '$$', 'African, Asian, Latin', true, false, true),
('Kabuki Cafe', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/kabuki-cafe/', '$', 'Asian, Japanese, Sushi', false, true, true),
('Kat Saka''s Kettle', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/kat-sakas-kettle/', '$', 'American', false, true, true),
('Katsura Grill', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/katsura-grill/', '$', 'Asian, Japanese', false, true, true),
('Landscape of Flavors', 'Disney''s Art of Animation Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/art-of-animation-resort/landscape-of-flavors/', '$', 'American', false, true, true),
('Lava Lounge', 'Disney''s Polynesian Village Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/polynesian-resort/lava-lounge/', '$', '', false, false, true),
('Le Petit Café', 'Disney''s Riviera Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/riviera-resort/le-petit-cafe/', '$', 'French', false, false, true),
('Leaky Tiki', 'Disney''s Polynesian Village Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/polynesian-resort/leaky-tiki/', '$', '', false, false, true),
('Les Halles Boulangerie-Patisserie', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/les-halles-boulangerie-patisserie/', '$', 'French', false, true, true),
('Lotus Blossom Café', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/lotus-blossom-cafe/', '$', 'Chinese', false, true, true),
('Lottawatta Lodge', 'Blizzard Beach', 'Park', 'https://disneyworld.disney.go.com/dining/blizzard-beach/lottawatta-lodge/', '$', 'American', false, true, true),
('The Lunching Pad', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/lunching-pad/', '$', 'American', false, true, true),
('Mango Joe''s', 'Typhoon Lagoon', 'Park', 'https://disneyworld.disney.go.com/dining/typhoon-lagoon/mango-joes/', '$', 'American', false, true, true),
('Martha''s Vineyard Lounge', 'Disney''s Beach Club Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/beach-club-resort/marthas-vineyard/', '$', 'American', false, false, true),
('Maya Grill', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/maya-grill/', '$$', 'Latin, Mexican', false, false, true),
('Milk Stand', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/milk-stand/', '$', '', false, true, true),
('Minnies Kitchen', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/minnies-kitchen/', '$$', 'American', true, false, true),
('Muddy Rivers Pool Bar', 'Disney''s Port Orleans Resort - Riverside', 'Resort', 'https://disneyworld.disney.go.com/dining/port-orleans-resort-riverside/muddy-rivers/', '$', 'American', false, true, true),
('Nomad Lounge', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/nomad-lounge/', '$$', '', false, false, true),
('Oasis Bar & Grill', 'Disney''s Polynesian Village Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/polynesian-resort/oasis-bar-and-grill/', '$', 'American', false, true, true),
('Oga''s Cantina', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/ogas-cantina/', '$$', 'American', true, false, true),
('On the Rocks Pool Bar', 'Disney''s Saratoga Springs Resort & Spa', 'Resort', 'https://disneyworld.disney.go.com/dining/saratoga-springs-resort-and-spa/on-the-rocks/', '$', 'American', false, true, true),
('Outer Rim', 'Disney''s Contemporary Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/contemporary-resort/outer-rim/', '$', 'American', false, false, true),
('Pecos Bill Tall Tale Inn and Cafe', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/pecos-bill-tall-tale-inn-and-cafe/', '$', 'American, Mexican', false, true, true),
('PizzeRizzo', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/pizzerizzo/', '$', 'American, Italian', false, true, true),
('Pizzafari', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/pizzafari/', '$', 'American, Italian', false, true, true),
('Planet Hollywood Observatory', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/planet-hollywood-observatory/', '$$', 'American', false, false, true),
('Primo Piatto', 'Disney''s Riviera Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/riviera-resort/primo-piatto/', '$', 'American, Italian', false, true, true),
('Refreshment Outpost', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/refreshment-outpost/', '$', 'American', false, true, true),
('Refreshment Port', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/refreshment-port/', '$', 'American', false, true, true),
('Restoration Hardware Cafe', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/rh-rooftop-restaurant/', '$$', '', false, false, true),
('Restaurantosaurus', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/restaurantosaurus/', '$', 'American', false, true, true),
('Rix Sports Bar & Grill', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/rix-lounge/', '$', 'American', false, false, true),
('River Roost', 'Disney''s Port Orleans Resort - Riverside', 'Resort', 'https://disneyworld.disney.go.com/dining/port-orleans-resort-riverside/river-roost/', '$', 'American', false, false, true),
('Riverside Mill Food Court', 'Disney''s Port Orleans Resort - Riverside', 'Resort', 'https://disneyworld.disney.go.com/dining/port-orleans-resort-riverside/riverside-mill-food-court/', '$', 'American', false, true, true),
('Ronto Roasters', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/ronto-roasters/', '$', 'American', false, true, true),
('Saber''s Quenchers', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/sabers-quenchers/', '$', 'American', false, true, true),
('Sassagoula Floatworks & Food Factory', 'Disney''s Port Orleans Resort - French Quarter', 'Resort', 'https://disneyworld.disney.go.com/dining/port-orleans-resort-french-quarter/sassagoula-floatworks/', '$', 'American, Cajun/Creole', false, true, true),
('Satu''li Canteen', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/satuli-canteen/', '$', 'American, Asian', false, true, true),
('Siestas Cantina', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/siestas-cantina/', '$', 'American, Mexican', false, true, true),
('Sleepy Hollow', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/sleepy-hollow/', '$', 'American', false, true, true),
('Sommerfest', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/sommerfest/', '$', 'German', false, true, true),
('Spice Road Table', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/spice-road-table/', '$$', 'Mediterranean, Moroccan', true, false, true),
('Splitsville Dining Room', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/splitsville-luxury-lanes/', '$$', 'American, Sushi', false, false, true),
('Sprinkles', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/sprinkles/', '$', 'American', false, true, true),
('Starbucks West Side', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/starbucks-west-side/', '$', 'American', false, true, true),
('STK Orlando', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/stk-orlando/', '$$$', 'American, Steakhouse', true, false, true),
('Storybook Treats', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/storybook-treats/', '$', 'American', false, true, true),
('Sunshine Seasons', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/sunshine-seasons/', '$', 'American, Asian', false, true, true),
('Sunshine Tree Terrace', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/sunshine-tree-terrace/', '$', 'American', false, true, true),
('Tangierine Café', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/tangierine-cafe/', '$', 'Moroccan', false, true, true),
('Tea Traders Café by Joffrey''s', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/tea-traders-cafe/', '$', '', false, true, true),
('The Daily Poutine', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/daily-poutine/', '$', '', false, true, true),
('The Friar''s Nook', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/friars-nook/', '$', 'American', false, true, true),
('The Mara', 'Disney''s Animal Kingdom Lodge', 'Resort', 'https://disneyworld.disney.go.com/dining/animal-kingdom-lodge/mara/', '$', 'African, American', false, true, true),
('The Polite Pig', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/polite-pig/', '$$', 'American, Barbecue', false, true, true),
('The Trolley Car Café', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/trolley-car-cafe/', '$', 'American', false, true, true),
('Three Bridges Bar & Grill at Villa del Lago', 'Disney''s Coronado Springs Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/coronado-springs-resort/three-bridges-bar-grill/', '$$', 'American', false, false, true),
('Topolino''s Terrace - Flavors of the Riviera', 'Disney''s Riviera Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/riviera-resort/topolinos-terrace/', '$$$', 'Italian, Mediterranean', true, false, true),
('Tortuga Tavern', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/tortuga-tavern/', '$', 'American, Mexican', false, true, true),
('Trader Sam''s Grog Grotto', 'Disney''s Polynesian Village Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/polynesian-resort/trader-sams-grog-grotto/', '$$', 'Polynesian', false, false, true),
('Trilo-Bites', 'Animal Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/animal-kingdom/trilo-bites/', '$', 'American', false, true, true),
('Vivoli il Gelato', 'Disney Springs', 'Disney Springs', 'https://disneyworld.disney.go.com/dining/disney-springs/vivoli-il-gelato/', '$', 'Italian', false, true, true),
('Warming Hut', 'Blizzard Beach', 'Park', 'https://disneyworld.disney.go.com/dining/blizzard-beach/warming-hut/', '$', 'American', false, true, true),
('Westward Ho', 'Magic Kingdom', 'Park', 'https://disneyworld.disney.go.com/dining/magic-kingdom/westward-ho/', '$', 'American', false, true, true),
('Woody''s Lunch Box', 'Hollywood Studios', 'Park', 'https://disneyworld.disney.go.com/dining/hollywood-studios/woodys-lunch-box/', '$', 'American', false, true, true),
('Yorkshire County Fish Shop', 'EPCOT', 'Park', 'https://disneyworld.disney.go.com/dining/epcot/yorkshire-county-fish-shop/', '$', 'British, Seafood', false, true, true),
('Leaning Palms', 'Typhoon Lagoon', 'Park', 'https://disneyworld.disney.go.com/dining/typhoon-lagoon/leaning-palms/', '$', 'American', false, true, true),
('Lowtide Lou''s', 'Typhoon Lagoon', 'Park', 'https://disneyworld.disney.go.com/dining/typhoon-lagoon/lowtide-lous/', '$', 'American', false, true, true),
('Snowy Sundae at Polar Pub', 'Blizzard Beach', 'Park', 'https://disneyworld.disney.go.com/dining/blizzard-beach/polar-pub/', '$', 'American', false, true, true),
('Typhoon Tilly''s', 'Typhoon Lagoon', 'Park', 'https://disneyworld.disney.go.com/dining/typhoon-lagoon/typhoon-tillys/', '$', 'American, Seafood', false, true, true),
('Happy Landings Ice Cream', 'Typhoon Lagoon', 'Park', 'https://disneyworld.disney.go.com/dining/typhoon-lagoon/happy-landings-ice-cream/', '$', 'American', false, true, true),
('Drop Off Pool Bar', 'Disney''s Art of Animation Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/art-of-animation-resort/drop-off-pool-bar/', '$', 'American', false, true, true),
('Grandstand Spirits Pool Bar', 'Disney''s All-Star Sports Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/all-star-sports-resort/grandstand-spirits/', '$', 'American', false, true, true),
('Singing Spirits Pool Bar', 'Disney''s All-Star Music Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/all-star-music-resort/singing-spirits-pool-bar/', '$', 'American', false, true, true),
('Silver Screen Spirits Pool Bar', 'Disney''s All-Star Movies Resort', 'Resort', 'https://disneyworld.disney.go.com/dining/all-star-movies-resort/silver-screen-spirits/', '$', 'American', false, true, true);