INSERT INTO public.headsup_words (word, category) VALUES
('Dumbo', 'animals'),
('Bambi', 'animals'),
('Simba', 'animals'),
('Thumper', 'animals'),
('Flower', 'animals'),
('Timon', 'animals'),
('Pumbaa', 'animals'),
('Zazu', 'animals'),
('Nala', 'animals'),
('Mufasa', 'animals'),
('Sarabi', 'animals'),
('Slinky Dog', 'animals'),
('Rex', 'animals'),
('Hamm', 'animals'),
('Bullseye', 'animals'),
('Flounder', 'animals'),
('Sebastian', 'animals'),
('Scuttle', 'animals'),
('Abu', 'animals'),
('Rajah', 'animals'),
('Iago', 'animals'),
('Pascal', 'animals'),
('Maximus', 'animals'),
('Meeko', 'animals'),
('Percy', 'animals'),
('Cri-Kee', 'animals'),
('Mushu', 'animals'),
('Khan', 'animals'),
('Pegasus', 'animals'),
('Phil', 'animals'),
('Angus', 'animals'),
('Figaro', 'animals'),
('Cleo', 'animals'),
('Gideon', 'animals'),
('Honest John', 'animals'),
('Monstro', 'animals'),
('Jaq', 'animals'),
('Gus', 'animals'),
('Perdita', 'animals'),
('Pongo', 'animals'),
('Lucky', 'animals'),
('Patch', 'animals'),
('Rolly', 'animals'),
('Tod', 'animals'),
('Copper', 'animals'),
('Winnie the Pooh', 'animals'),
('Piglet', 'animals'),
('Tigger', 'animals'),
('Eeyore', 'animals'),
('Kanga', 'animals'),
('Roo', 'animals'),
('Rabbit', 'animals'),
('Bernard', 'animals'),
('Miss Bianca', 'animals'),
('Lady', 'animals'),
('Tramp', 'animals'),
('Jock', 'animals'),
('Trusty', 'animals'),
('Duchess', 'animals'),
('Thomas O''Malley', 'animals'),
('Marie', 'animals'),
('Toulouse', 'animals'),
('Berlioz', 'animals'),
('Scat Cat', 'animals'),
('Kaa', 'animals'),
('Baloo', 'animals'),
('Bagheera', 'animals'),
('Shere Khan', 'animals'),
('King Louie', 'animals'),
('Hathi Jr.', 'animals'),
('Colonel Hathi', 'animals'),
('Little John', 'animals'),
('Sir Hiss', 'animals'),
('Gurgi', 'animals'),
('Hen Wen', 'animals'),
('Darkwing Duck', 'animals'),
('Launchpad McQuack', 'animals'),
('Gizmoduck', 'animals'),
('Chip', 'animals'),
('Dale', 'animals'),
('Gadget Hackwrench', 'animals'),
('Monterey Jack', 'animals'),
('Zipper', 'animals'),
('Goofy', 'animals'),
('Pluto', 'animals'),
('Mickey Mouse', 'animals'),
('Minnie Mouse', 'animals'),
('Donald Duck', 'animals'),
('Daisy Duck', 'animals'),
('Scrooge McDuck', 'animals'),
('Huey', 'animals'),
('Dewey', 'animals'),
('Louie', 'animals'),
('Max Goof', 'animals'),
('Stitch', 'animals'),
('Trixie', 'animals'),
('Bing Bong', 'animals'),
('Maleficent', 'animals'),
('Chernabog', 'animals'),
('Jack Skellington', 'animals'),
('Zero', 'animals'),
('Oogie Boogie', 'animals'),
('Sally', 'animals'),
('Kraken', 'animals'),
('Davy Jones', 'animals'),
('Nemo', 'animals'),
('Dory', 'animals'),
('Marlin', 'animals'),
('Bruce', 'animals'),
('Crush', 'animals'),
('Squirt', 'animals'),
('Mr. Ray', 'animals'),
('Hank', 'animals'),
('Bailey', 'animals'),
('Destiny', 'animals'),
('Gill', 'animals'),
('Bloat', 'animals'),
('Bubbles', 'animals'),
('Deb', 'animals'),
('Jacques', 'animals'),
('Peach', 'animals'),
('Nigel', 'animals'),
('Sully', 'animals'),
('Mike Wazowski', 'animals'),
('Boo', 'animals'),
('Randall Boggs', 'animals'),
('Roz', 'animals'),
('Celia Mae', 'animals'),
('WALL-E', 'animals'),
('EVE', 'animals'),
('M-O', 'animals'),
('Flik', 'animals'),
('Atta', 'animals'),
('Heimlich', 'animals'),
('Slim', 'animals'),
('Francis', 'animals'),
('Dim', 'animals'),
('Hopper', 'animals'),
('Remy', 'animals'),
('Linguini', 'animals'),
('Django', 'animals'),
('Emile', 'animals'),
('Colette Tatou', 'animals'),
('Auguste Gusteau', 'animals'),
('Lightning McQueen', 'animals'),
('Mater', 'animals'),
('Doc Hudson', 'animals'),
('Sally Carrera', 'animals'),
('Luigi', 'animals'),
('Guido', 'animals'),
('Chick Hicks', 'animals'),
('Jackson Storm', 'animals'),
('Cruz Ramirez', 'animals'),
('Banshee', 'animals'),
('Thanator', 'animals'),
('Great Leonopteryx', 'animals'),
('Viperwolf', 'animals'),
('Direhorse', 'animals'),
('Peter Pan', 'characters'),
('Tinker Bell', 'characters'),
('Captain Hook', 'characters'),
('Mr. Smee', 'characters'),
('Wendy Darling', 'characters'),
('John Darling', 'characters'),
('Michael Darling', 'characters'),
('Alice', 'characters'),
('Mad Hatter', 'characters'),
('Cheshire Cat', 'characters'),
('Queen of Hearts', 'characters'),
('White Rabbit', 'characters'),
('Cinderella', 'characters'),
('Prince Charming', 'characters'),
('Jaq and Gus', 'characters'),
('Fairy Godmother', 'characters'),
('Lady Tremaine', 'characters'),
('Anastasia', 'characters'),
('Drizella', 'characters'),
('Snow White', 'characters'),
('Dopey', 'characters'),
('Grumpy', 'characters'),
('Sneezy', 'characters'),
('Bashful', 'characters'),
('Happy', 'characters'),
('Sleepy', 'characters'),
('Doc', 'characters'),
('The Evil Queen', 'characters'),
('Aurora', 'characters'),
('Prince Phillip', 'characters'),
('Flora', 'characters'),
('Fauna', 'characters'),
('Merryweather', 'characters'),
('Ariel', 'characters'),
('Prince Eric', 'characters'),
('Ursula', 'characters'),
('King Triton', 'characters'),
('Belle', 'characters'),
('Beast', 'characters'),
('Lumiere', 'characters'),
('Cogsworth', 'characters'),
('Mrs. Potts', 'characters'),
('Gaston', 'characters'),
('Jasmine', 'characters'),
('Aladdin', 'characters'),
('Genie', 'characters'),
('Jafar', 'characters'),
('Pocahontas', 'characters'),
('John Smith', 'characters'),
('Flit', 'characters'),
('Mulan', 'characters'),
('Shang', 'characters'),
('Fa Zhou', 'characters'),
('Li Shang', 'characters'),
('Tiana', 'characters'),
('Prince Naveen', 'characters'),
('Louis', 'characters'),
('Ray', 'characters'),
('Dr. Facilier', 'characters'),
('Mama Odie', 'characters'),
('Rapunzel', 'characters'),
('Flynn Rider', 'characters'),
('Mother Gothel', 'characters'),
('Merida', 'characters'),
('Queen Elinor', 'characters'),
('King Fergus', 'characters'),
('Mowgli', 'characters'),
('Tarzan', 'characters'),
('Jane Porter', 'characters'),
('Kermit the Frog', 'characters'),
('Miss Piggy', 'characters'),
('Fozzie Bear', 'characters'),
('Gonzo', 'characters'),
('Olaf', 'characters'),
('Elsa', 'characters'),
('Anna', 'characters'),
('Kristoff', 'characters'),
('Sven', 'characters'),
('Hans', 'characters'),
('Moana', 'characters'),
('Maui', 'characters'),
('Pua', 'characters'),
('Heihei', 'characters'),
('Chief Tui', 'characters'),
('Sina', 'characters'),
('Lilo', 'characters'),
('Nani', 'characters'),
('Jumba Jookiba', 'characters'),
('Pleakley', 'characters'),
('Pinocchio', 'characters'),
('Jiminy Cricket', 'characters'),
('Geppetto', 'characters'),
('Blue Fairy', 'characters'),
('Stromboli', 'characters'),
('Timothy Q. Mouse', 'characters'),
('Mrs. Jumbo', 'characters'),
('Great Prince of the Forest', 'characters'),
('Cruella De Vil', 'characters'),
('Roger Radcliffe', 'characters'),
('Anita Radcliffe', 'characters'),
('Madame Medusa', 'characters'),
('Penny', 'characters'),
('Elliot', 'characters'),
('Pete''s Dragon', 'characters'),
('Chip and Dale', 'characters'),
('Hercules', 'characters'),
('Megara', 'characters'),
('Hades', 'characters'),
('Pain and Panic', 'characters'),
('Zeus', 'characters'),
('Emperor Kuzco', 'characters'),
('Kronk', 'characters'),
('Yzma', 'characters'),
('Pacha', 'characters'),
('Quasimodo', 'characters'),
('Esmeralda', 'characters'),
('Phoebus', 'characters'),
('Frollo', 'characters'),
('Victor Hugo', 'characters'),
('Hugo', 'characters'),
('Laverne', 'characters'),
('Wreck-It Ralph', 'characters'),
('Vanellope von Schweetz', 'characters'),
('Fix-It Felix Jr.', 'characters'),
('Sergeant Calhoun', 'characters'),
('King Candy', 'characters'),
('Baymax', 'characters'),
('Hiro Hamada', 'characters'),
('GoGo Tomago', 'characters'),
('Wasabi', 'characters'),
('Honey Lemon', 'characters'),
('Fred', 'characters'),
('Mirabel Madrigal', 'characters'),
('Bruno Madrigal', 'characters'),
('Luisa Madrigal', 'characters'),
('Isabela Madrigal', 'characters'),
('Abuela Alma', 'characters'),
('Robin Hood', 'characters'),
('Maid Marian', 'characters'),
('Prince John', 'characters'),
('Dole Whip', 'food'),
('Turkey Leg', 'food'),
('Mickey Ice Cream Bar', 'food'),
('Churro', 'food'),
('Mickey Waffle', 'food'),
('Corn Dog Nuggets', 'food'),
('Ronto Wrap', 'food'),
('Grey Stuff', 'food'),
('LeFou''s Brew', 'food'),
('School Bread', 'food'),
('Mickey Pretzel', 'food'),
('Citrus Swirl', 'food'),
('Pineapple Upside Down Cake', 'food'),
('Tonga Toast', 'food'),
('Ohana Bread Pudding', 'food'),
('Macaron', 'food'),
('Beignets', 'food'),
('Dole Whip Float', 'food'),
('Night Blossom', 'food'),
('Blue Milk', 'food'),
('Green Milk', 'food'),
('Butterbeer', 'food'),
('Num Num Cookie', 'food'),
('Spring Roll', 'food'),
('Cheeseburger Spring Rolls', 'food'),
('Popcorn Bucket', 'food'),
('Dole Whip Nachos', 'food'),
('Peter Pan Float', 'food'),
('Cookes of Dublin Fish and Chips', 'food'),
('Raglan Road', 'food'),
('Joffrey''s Coffee', 'food'),
('Pongu Pongu', 'food'),
('Sunshine Smoothie', 'food'),
('Cookie Butter Waffles', 'food'),
('Pork Belly Bao Buns', 'food'),
('Totchos', 'food'),
('Bengal Barbecue Skewers', 'food'),
('Clam Chowder Bread Bowl', 'food'),
('Lobster Roll', 'food'),
('Magic Kingdom Funnel Cake', 'food'),
('Croque Monsieur', 'food'),
('Monte Cristo Sandwich', 'food'),
('Croissant Donut', 'food'),
('Gaston''s Tavern', 'food'),
('Oga''s Cantina', 'food'),
('Flame Tree Barbecue', 'food'),
('Woody''s Lunch Box', 'food'),
('Docking Bay 7', 'food'),
('Satu''li Canteen', 'food'),
('Be Our Guest Restaurant', 'food'),
('Cinderella''s Royal Table', 'food'),
('The Crystal Palace', 'food'),
('1900 Park Fare', 'food'),
('Chef Mickey''s', 'food'),
('Ohana', 'food'),
('Victoria and Albert''s', 'food'),
('Flying Fish', 'food'),
('Topolino''s Terrace', 'food'),
('California Grill', 'food'),
('Le Cellier Steakhouse', 'food'),
('Tusker House', 'food'),
('Boma', 'food'),
('Sanaa', 'food'),
('Jiko', 'food'),
('Artist Point', 'food'),
('Yachtsman Steakhouse', 'food'),
('Narcoossee''s', 'food'),
('Tokyo Dining', 'food'),
('Teppan Edo', 'food'),
('San Angel Inn', 'food'),
('Rose and Crown', 'food'),
('Via Napoli', 'food'),
('Space 220', 'food'),
('La Hacienda de San Angel', 'food'),
('Monsieur Paul', 'food'),
('Biergarten Restaurant', 'food'),
('Garden Grill', 'food'),
('Coral Reef Restaurant', 'food'),
('Akershus Royal Banquet Hall', 'food'),
('Morocco Pavilion', 'food'),
('China Pavilion', 'food'),
('Japan Pavilion', 'food'),
('Ale & Compass', 'food'),
('Boatwright''s Dining Hall', 'food'),
('Trail''s End Restaurant', 'food'),
('Whispering Canyon Cafe', 'food'),
('Liberty Tree Tavern', 'food'),
('The Plaza Restaurant', 'food'),
('Tony''s Town Square Restaurant', 'food'),
('Jungle Navigation Co.', 'food'),
('Skipper Canteen', 'food'),
('Pecos Bill Tall Tale Inn', 'food'),
('Columbia Harbour House', 'food'),
('Casey''s Corner', 'food'),
('Sleepy Hollow', 'food'),
('Cosmic Ray''s Starlight Cafe', 'food'),
('Pinocchio Village Haus', 'food'),
('The Friar''s Nook', 'food'),
('Storybook Treats', 'food'),
('Aloha Isle', 'food'),
('Main Street Bakery', 'food'),
('Earl of Sandwich', 'food'),
('D-Luxe Burger', 'food'),
('The Polite Pig', 'food'),
('Blaze Fast-Fire''d Pizza', 'food'),
('Morimoto Asia', 'food'),
('The Boathouse', 'food'),
('Jaleo', 'food'),
('Homecomin''', 'food'),
('Wine Bar George', 'food'),
('Frontera Cocina', 'food'),
('Planet Hollywood', 'food'),
('Rainforest Cafe', 'food'),
('T-REX', 'food'),
('Wolfgang Puck Bar and Grill', 'food'),
('Erin McKenna''s Bakery NYC', 'food'),
('Sprinkles Cupcakes', 'food'),
('Ghirardelli Soda Fountain', 'food'),
('Chicken Guy!', 'food'),
('Everglazed Donuts', 'food'),
('Gideon''s Bakehouse', 'food'),
('AristoCrepes', 'food'),
('Swirls on the Water', 'food'),
('Auntie Gravity''s', 'food'),
('Regal Eagle Smokehouse', 'food'),
('ABC Commissary', 'food'),
('Backlot Express', 'food'),
('PizzeRizzo', 'food'),
('Sci-Fi Dine-In Theater', 'food'),
('50''s Prime Time Cafe', 'food'),
('Hollywood and Vine', 'food'),
('Mama Melrose''s', 'food'),
('The Hollywood Brown Derby', 'food'),
('Baseline Tap House', 'food'),
('Roundup Rodeo BBQ', 'food'),
('Restaurantosaurus', 'food'),
('Yak and Yeti', 'food'),
('Nomad Lounge', 'food'),
('Eight Spoon Cafe', 'food'),
('Harambe Market', 'food'),
('Mr. Kamal''s Seasoned Fries', 'food'),
('Trader Sam''s Grog Grotto', 'food'),
('Walt Disney', 'history'),
('Roy O. Disney', 'history'),
('Lillian Disney', 'history'),
('Ub Iwerks', 'history'),
('Mary Blair', 'history'),
('Marc Davis', 'history'),
('Joe Rohde', 'history'),
('Bob Iger', 'history'),
('Michael Eisner', 'history'),
('Frank Wells', 'history'),
('Roy E. Disney', 'history'),
('The Nine Old Men', 'history'),
('Ollie Johnston', 'history'),
('Frank Thomas', 'history'),
('Les Clark', 'history'),
('Woolie Reitherman', 'history'),
('Ward Kimball', 'history'),
('Milt Kahl', 'history'),
('Eric Larson', 'history'),
('John Lounsbery', 'history'),
('Imagineering', 'history'),
('Audio-Animatronics', 'history'),
('Steamboat Willie', 'history'),
('Oswald the Lucky Rabbit', 'history'),
('Laugh-O-Gram Studio', 'history'),
('Hyperion Studio', 'history'),
('Walt Disney Studios', 'history'),
('Burbank Studio', 'history'),
('Disneyland Opening Day', 'history'),
('Black Sunday', 'history'),
('Walt Disney World Opening', 'history'),
('EPCOT Center Opening', 'history'),
('Tokyo Disneyland Opening', 'history'),
('Euro Disneyland Opening', 'history'),
('Hong Kong Disneyland Opening', 'history'),
('Shanghai Disneyland Opening', 'history'),
('The Florida Project', 'history'),
('Reedy Creek Improvement District', 'history'),
('Mineral King Ski Resort', 'history'),
('Discovery Bay', 'history'),
('WEDway PeopleMover', 'history'),
('Carousel of Progress', 'history'),
('Walt Disney''s Apartment', 'history'),
('Club 33', 'history'),
('The Utilidors', 'history'),
('Horizons', 'history'),
('World of Motion', 'history'),
('If You Had Wings', 'history'),
('The ExtraTERRORestrial', 'history'),
('Mr. Toad''s Wild Ride', 'history'),
('20,000 Leagues Under the Sea', 'history'),
('Adventure Thru Inner Space', 'history'),
('PeopleMover', 'history'),
('The Living Seas', 'history'),
('Wonders of Life Pavilion', 'history'),
('The Land Pavilion', 'history'),
('Innoventions', 'history'),
('Walt Disney Presents', 'history'),
('One Man''s Dream', 'history'),
('The Disney Legend Award', 'history'),
('The Disney Renaissance', 'history'),
('Walt Disney Animation Studios', 'history'),
('Pixar Acquisition', 'history'),
('Marvel Acquisition', 'history'),
('Lucasfilm Acquisition', 'history'),
('21st Century Fox Acquisition', 'history'),
('Disney Channel Launch', 'history'),
('The Mickey Mouse Club', 'history'),
('The Wonderful World of Disney', 'history'),
('Walt Disney''s Disneyland TV Show', 'history'),
('ABC Merger', 'history'),
('ESPN Acquisition', 'history'),
('Disney Cruise Line Launch', 'history'),
('Disney Vacation Club', 'history'),
('Annual Passholder', 'history'),
('Magic Key', 'history'),
('MagicBand', 'history'),
('MagicBand+', 'history'),
('FastPass', 'history'),
('FastPass+', 'history'),
('Genie+', 'history'),
('Lightning Lane', 'history'),
('My Disney Experience', 'history'),
('Play Disney Parks App', 'history'),
('Disney PhotoPass', 'history'),
('Memory Maker', 'history'),
('Disney Skyliner', 'history'),
('Disney Monorail', 'history'),
('Disney Magical Express', 'history'),
('Mears Connect', 'history'),
('Walt Disney World Railroad', 'history'),
('Tomorrowland Transit Authority', 'history'),
('Friendship Boats', 'history'),
('Disney Springs Transformation', 'history'),
('The Marketplace', 'history'),
('Walt Disney World Marathon', 'history'),
('Epcot International Food and Wine', 'history'),
('Epcot Flower and Garden Festival', 'history'),
('Mickey''s Not-So-Scary Halloween', 'history'),
('Mickey''s Very Merry Christmas', 'history'),
('Star Wars Celebration', 'history'),
('D23 Expo', 'history'),
('Bob Chapek', 'history'),
('Josh D''Amaro', 'history'),
('Tom Staggs', 'history'),
('Marty Sklar', 'history'),
('Tony Baxter', 'history'),
('John Hench', 'history'),
('Harriet Burns', 'history'),
('Blaine Gibson', 'history'),
('X. Atencio', 'history'),
('Buddy Baker', 'history'),
('Richard Sherman', 'history'),
('Robert Sherman', 'history'),
('Alan Menken', 'history'),
('Howard Ashman', 'history'),
('Glass Slipper', 'items'),
('Magic Carpet', 'items'),
('Magic Mirror', 'items'),
('Poison Apple', 'items'),
('Trident', 'items'),
('Genie''s Lamp', 'items'),
('Enchanted Rose', 'items'),
('Flying Carpet', 'items'),
('Carpet Bag', 'items'),
('Ruby Slippers', 'items'),
('Sorcerer''s Hat', 'items'),
('Mickey Ears', 'items'),
('Minnie Bow', 'items'),
('Donald''s Sailor Hat', 'items'),
('Infinity Gauntlet', 'items'),
('Lightsaber', 'items'),
('Blaster', 'items'),
('Thermal Detonator', 'items'),
('Holocron', 'items'),
('Kyber Crystal', 'items'),
('Darksaber', 'items'),
('Beskar Armor', 'items'),
('Mandalorian Helmet', 'items'),
('Stormtrooper Armor', 'items'),
('Carbonite', 'items'),
('Death Star Plans', 'items'),
('Golden Idol', 'items'),
('Holy Grail', 'items'),
('Ark of the Covenant', 'items'),
('Crystal Skull', 'items'),
('DoomBuggy', 'items'),
('Hitchhiking Ghosts', 'items'),
('999 Happy Haunts', 'items'),
('Madame Leota', 'items'),
('Hatbox Ghost', 'items'),
('Constance Hatchaway', 'items'),
('Haunted Mansion Stretching Room', 'items'),
('Hidden Mickey', 'items'),
('MagicBand', 'items'),
('Annual Pass', 'items'),
('Park Hopper', 'items'),
('Dining Plan', 'items'),
('Magic Kingdom Map', 'items'),
('Disney Pin', 'items'),
('Disney Trading Pin', 'items'),
('Pressed Penny', 'items'),
('Spirit Jersey', 'items'),
('Minnie Ears Headband', 'items'),
('Bubble Wand', 'items'),
('Glow Stick', 'items'),
('Mickey Balloon', 'items'),
('Sword in the Stone', 'items'),
('Excalibur', 'items'),
('Pixie Dust', 'items'),
('Fairy Wand', 'items'),
('Magic Wand', 'items'),
('Spinning Wheel', 'items'),
('Pumpkin Carriage', 'items'),
('Seven Dwarfs'' Pickaxe', 'items'),
('Snow Globe', 'items'),
('Music Box', 'items'),
('Magic Beans', 'items'),
('Golden Harp', 'items'),
('Brave Little Toaster', 'items'),
('Mickey''s Sorcerer Hat', 'items'),
('Fantasia Hat', 'items'),
('Dreamfinder''s Top Hat', 'items'),
('Figment''s Purple Dragon', 'items'),
('Spaceship Earth Sphere', 'items'),
('Cinderella Castle Model', 'items'),
('Partners Statue', 'items'),
('Four Keys', 'items'),
('Compass', 'items'),
('Spyglass', 'items'),
('Treasure Map', 'items'),
('Pirate Flag', 'items'),
('Jolly Roger', 'items'),
('Captain Hook''s Hook', 'items'),
('Peter Pan''s Shadow', 'items'),
('Tinker Bell''s Wings', 'items'),
('Woody''s Hat', 'items'),
('Buzz Lightyear''s Wings', 'items'),
('Buzz Lightyear''s Laser', 'items'),
('Jessie''s Hat', 'items'),
('Bo Peep''s Crook', 'items'),
('Mr. Potato Head''s Parts', 'items'),
('Etch A Sketch', 'items'),
('RC Car', 'items'),
('Pizza Planet Truck', 'items'),
('Toy Story Ball', 'items'),
('Alien Claw', 'items'),
('Andy''s Cowboy Hat', 'items'),
('Monsters Inc. Door', 'items'),
('Scream Canister', 'items'),
('Mike''s Hard Hat', 'items'),
('Sully''s Fur', 'items'),
('Boo''s Door', 'items'),
('Nemo''s Anemone', 'items'),
('Dory''s Shell', 'items'),
('Aqua Scooter', 'items'),
('EVE''s Plant', 'items'),
('WALL-E''s Cube', 'items'),
('WALL-E''s Cockroach', 'items'),
('Lightning McQueen''s Piston Cup', 'items'),
('Radiator Springs Sign', 'items'),
('Cars Land Neon', 'items'),
('Remy''s Chef Hat', 'items'),
('Gusteau''s Restaurant Sign', 'items'),
('Incredibles Super Suit', 'items'),
('Elastigirl''s Mask', 'items'),
('Edna Mode''s Glasses', 'items'),
('Jack-Jack''s Cookie', 'items'),
('Carl''s Cane', 'items'),
('Ellie Badge', 'items'),
('Russell''s Sash', 'items'),
('UP House Balloons', 'items'),
('Grape Soda Pin', 'items'),
('Inside Out Memory Orb', 'items'),
('Core Memory', 'items'),
('Console', 'items'),
('Imagination Land', 'items'),
('Soul''s Earth Pass', 'items'),
('Joe''s Hat', 'items'),
('Coco Guitar', 'items'),
('Marigold Bridge', 'items'),
('Encanto Candle', 'items'),
('Casita', 'items'),
('Pandora', 'locations'),
('Batuu', 'locations'),
('Neverland', 'locations'),
('Agrabah', 'locations'),
('Atlantica', 'locations'),
('Arendelle', 'locations'),
('Corona', 'locations'),
('Motunui', 'locations'),
('Prydain', 'locations'),
('Wonderland', 'locations'),
('Hundred Acre Wood', 'locations'),
('Sherwood Forest', 'locations'),
('Pride Rock', 'locations'),
('Skull Island', 'locations'),
('Treasure Planet', 'locations'),
('Monstropolis', 'locations'),
('Radiator Springs', 'locations'),
('Metroville', 'locations'),
('San Fransokyo', 'locations'),
('Zootopia', 'locations'),
('Sugar Rush', 'locations'),
('DunBroch', 'locations'),
('Kumandra', 'locations'),
('Encanto', 'locations'),
('New Mushroomton', 'locations'),
('Deep Space', 'locations'),
('Halloweentown', 'locations'),
('Christmas Town', 'locations'),
('London', 'locations'),
('Paris', 'locations'),
('Beast''s Castle', 'locations'),
('Prince Eric''s Castle', 'locations'),
('Sultan''s Palace', 'locations'),
('Olympus', 'locations'),
('Mount Olympus', 'locations'),
('The Underworld', 'locations'),
('China', 'locations'),
('The Bayou', 'locations'),
('New Orleans Square', 'locations'),
('Adventureland', 'locations'),
('Fantasyland', 'locations'),
('Tomorrowland', 'locations'),
('Frontierland', 'locations'),
('Liberty Square', 'locations'),
('Main Street U.S.A.', 'locations'),
('Toontown', 'locations'),
('Critter Country', 'locations'),
('Bear Country', 'locations'),
('Discovery Island', 'locations'),
('Dinoland U.S.A.', 'locations'),
('Africa', 'locations'),
('Asia', 'locations'),
('Pandora - The World of Avatar', 'locations'),
('Star Wars: Galaxy''s Edge', 'locations'),
('Toy Story Land', 'locations'),
('Sunset Boulevard', 'locations'),
('Hollywood Boulevard', 'locations'),
('Echo Lake', 'locations'),
('Animation Courtyard', 'locations'),
('World Showcase', 'locations'),
('Future World', 'locations'),
('World Celebration', 'locations'),
('World Discovery', 'locations'),
('World Nature', 'locations'),
('The Hub', 'locations'),
('Town Square', 'locations'),
('Crystal Palace', 'locations'),
('Swiss Family Treehouse', 'locations'),
('Tom Sawyer Island', 'locations'),
('Rivers of America', 'locations'),
('Bay Lake', 'locations'),
('Seven Seas Lagoon', 'locations'),
('Hourglass Lake', 'locations'),
('Crescent Lake', 'locations'),
('Disney Boardwalk', 'locations'),
('International Gateway', 'locations'),
('Camp Minnie-Mickey', 'locations'),
('Rafiki''s Planet Watch', 'locations'),
('Maharajah Jungle Trek', 'locations'),
('Gorilla Falls', 'locations'),
('Oasis', 'locations'),
('Tree of Life', 'locations'),
('Spaceship Earth', 'locations'),
('Cinderella Castle', 'locations'),
('Tower of Terror', 'locations'),
('Black Spire Outpost', 'locations'),
('Mos Eisley', 'locations'),
('Droid Depot', 'locations'),
('Savi''s Workshop', 'locations'),
('Buena Vista Street', 'locations'),
('Cars Land', 'locations'),
('Pixar Pier', 'locations'),
('Avengers Campus', 'locations'),
('Grizzly Peak', 'locations'),
('Hollywood Land', 'locations'),
('Pacific Wharf', 'locations'),
('Paradise Gardens Park', 'locations'),
('Sleeping Beauty Castle', 'locations'),
('Weenie', 'locations'),
('Partners Statue', 'locations'),
('Walt and Mickey Statue', 'locations'),
('The Lion King', 'movies'),
('Frozen', 'movies'),
('Toy Story', 'movies'),
('Finding Nemo', 'movies'),
('Encanto', 'movies'),
('The Little Mermaid', 'movies'),
('Coco', 'movies'),
('Tangled', 'movies'),
('Zootopia', 'movies'),
('Beauty and the Beast', 'movies'),
('Fantasia', 'movies'),
('Fantasia 2000', 'movies'),
('The Jungle Book', 'movies'),
('Pinocchio', 'movies'),
('Snow White and the Seven Dwarfs', 'movies'),
('Sleeping Beauty', 'movies'),
('Cinderella', 'movies'),
('Alice in Wonderland', 'movies'),
('Peter Pan', 'movies'),
('Lady and the Tramp', 'movies'),
('101 Dalmatians', 'movies'),
('The Aristocats', 'movies'),
('Robin Hood', 'movies'),
('The Rescuers', 'movies'),
('The Fox and the Hound', 'movies'),
('The Black Cauldron', 'movies'),
('The Great Mouse Detective', 'movies'),
('Oliver and Company', 'movies'),
('The Princess and the Frog', 'movies'),
('Wreck-It Ralph', 'movies'),
('Big Hero 6', 'movies'),
('Brave', 'movies'),
('Ralph Breaks the Internet', 'movies'),
('Wish', 'movies'),
('Strange World', 'movies'),
('Raya and the Last Dragon', 'movies'),
('Luca', 'movies'),
('Soul', 'movies'),
('Onward', 'movies'),
('Elemental', 'movies'),
('Turning Red', 'movies'),
('Lightyear', 'movies'),
('Bambi', 'movies'),
('Dumbo', 'movies'),
('The Sword in the Stone', 'movies'),
('The Many Adventures of Winnie the Pooh', 'movies'),
('The Rescuers Down Under', 'movies'),
('Pocahontas', 'movies'),
('Mulan', 'movies'),
('Tarzan', 'movies'),
('Atlantis: The Lost Empire', 'movies'),
('Lilo and Stitch', 'movies'),
('Treasure Planet', 'movies'),
('Brother Bear', 'movies'),
('Home on the Range', 'movies'),
('Chicken Little', 'movies'),
('Meet the Robinsons', 'movies'),
('Bolt', 'movies'),
('The Emperor''s New Groove', 'movies'),
('Dinosaur', 'movies'),
('Hercules', 'movies'),
('The Hunchback of Notre Dame', 'movies'),
('Moana', 'movies'),
('Saludos Amigos', 'movies'),
('The Three Caballeros', 'movies'),
('Make Mine Music', 'movies'),
('Fun and Fancy Free', 'movies'),
('Melody Time', 'movies'),
('The Adventures of Ichabod', 'movies'),
('Mary Poppins', 'movies'),
('Mary Poppins Returns', 'movies'),
('Bedknobs and Broomsticks', 'movies'),
('The Love Bug', 'movies'),
('Honey I Shrunk the Kids', 'movies'),
('Tron', 'movies'),
('Tron: Legacy', 'movies'),
('The Parent Trap', 'movies'),
('Freaky Friday', 'movies'),
('Pirates of the Caribbean', 'movies'),
('Hocus Pocus', 'movies'),
('Hocus Pocus 2', 'movies'),
('Enchanted', 'movies'),
('Disenchanted', 'movies'),
('National Treasure', 'movies'),
('The Haunted Mansion', 'movies'),
('Jungle Cruise', 'movies'),
('Cruella', 'movies'),
('Maleficent', 'movies'),
('Aladdin', 'movies'),
('The Lion King (2019)', 'movies'),
('Mulan (2020)', 'movies'),
('Kermit the Frog', 'muppets'),
('Miss Piggy', 'muppets'),
('Fozzie Bear', 'muppets'),
('Gonzo the Great', 'muppets'),
('Animal', 'muppets'),
('Scooter', 'muppets'),
('Rowlf the Dog', 'muppets'),
('Rizzo the Rat', 'muppets'),
('Pepe the King Prawn', 'muppets'),
('Sam Eagle', 'muppets'),
('Statler and Waldorf', 'muppets'),
('The Swedish Chef', 'muppets'),
('Dr. Bunsen Honeydew', 'muppets'),
('Beaker', 'muppets'),
('Dr. Teeth', 'muppets'),
('Floyd Pepper', 'muppets'),
('Janice', 'muppets'),
('Zoot', 'muppets'),
('Lips', 'muppets'),
('The Electric Mayhem', 'muppets'),
('Sweetums', 'muppets'),
('Robin the Frog', 'muppets'),
('Camilla the Chicken', 'muppets'),
('Bean Bunny', 'muppets'),
('Clifford', 'muppets'),
('Bobo the Bear', 'muppets'),
('Johnny Fiama', 'muppets'),
('Sal Minella', 'muppets'),
('Link Hogthrob', 'muppets'),
('Lew Zealand', 'muppets'),
('Crazy Harry', 'muppets'),
('Uncle Deadly', 'muppets'),
('Thog', 'muppets'),
('Beautiful Day Monster', 'muppets'),
('The Newsman', 'muppets'),
('Nigel the Director', 'muppets'),
('Annie Sue', 'muppets'),
('Walter', 'muppets'),
('Constantine', 'muppets'),
('Foo-Foo', 'muppets'),
('Gaffer the Cat', 'muppets'),
('Sprocket', 'muppets'),
('Gobo Fraggle', 'muppets'),
('Red Fraggle', 'muppets'),
('Wembley Fraggle', 'muppets'),
('Mokey Fraggle', 'muppets'),
('Boober Fraggle', 'muppets'),
('Traveling Matt', 'muppets'),
('The Trash Heap', 'muppets'),
('Doozers', 'muppets'),
('Gorgs', 'muppets'),
('Pa Gorg', 'muppets'),
('Ma Gorg', 'muppets'),
('Junior Gorg', 'muppets'),
('Cantus the Minstrel', 'muppets'),
('The Muppet Show', 'muppets'),
('The Muppet Movie', 'muppets'),
('The Great Muppet Caper', 'muppets'),
('The Muppets Take Manhattan', 'muppets'),
('Muppet Christmas Carol', 'muppets'),
('Muppet Treasure Island', 'muppets'),
('Muppets from Space', 'muppets'),
('The Muppets (2011)', 'muppets'),
('Muppets Most Wanted', 'muppets'),
('Muppets Haunted Mansion', 'muppets'),
('Muppet Babies', 'muppets'),
('The Muppets Mayhem', 'muppets'),
('Fraggle Rock', 'muppets'),
('Fraggle Rock: Back to the Rock', 'muppets'),
('The Dark Crystal', 'muppets'),
('Labyrinth', 'muppets'),
('Jim Henson', 'muppets'),
('Frank Oz', 'muppets'),
('Dave Goelz', 'muppets'),
('Steve Whitmire', 'muppets'),
('Jerry Nelson', 'muppets'),
('Richard Hunt', 'muppets'),
('Caroll Spinney', 'muppets'),
('Big Bird', 'muppets'),
('Elmo', 'muppets'),
('Cookie Monster', 'muppets'),
('Oscar the Grouch', 'muppets'),
('Grover', 'muppets'),
('Bert', 'muppets'),
('Ernie', 'muppets'),
('The Count', 'muppets'),
('Snuffleupagus', 'muppets'),
('Abby Cadabby', 'muppets'),
('Telly Monster', 'muppets'),
('Rosita', 'muppets'),
('Zoe', 'muppets'),
('Murray Monster', 'muppets'),
('Baby Bear', 'muppets'),
('Prairie Dawn', 'muppets'),
('Herry Monster', 'muppets'),
('Guy Smiley', 'muppets'),
('Barkley', 'muppets'),
('Slimey the Worm', 'muppets'),
('Two-Headed Monster', 'muppets'),
('Frazzle', 'muppets'),
('Honkers', 'muppets'),
('Dingers', 'muppets'),
('Muppet Theater', 'muppets'),
('MuppetVision 3D', 'muppets'),
('Pigs in Space', 'muppets'),
('Veterinarian''s Hospital', 'muppets'),
('Bear on Patrol', 'muppets'),
('The Happiness Hotel', 'muppets'),
('Muppet Labs', 'muppets'),
('The Rainbow Connection', 'muppets'),
('Movin'' Right Along', 'muppets'),
('I''m Going to Go Back There Someday', 'muppets'),
('Mahna Mahna', 'muppets'),
('Bein'' Green', 'muppets'),
('Wocka Wocka!', 'muppets'),
('Life''s a Happy Song', 'muppets'),
('Together Again', 'muppets'),
('Magic Kingdom', 'parks'),
('EPCOT', 'parks'),
('Hollywood Studios', 'parks'),
('Animal Kingdom', 'parks'),
('Main Street USA', 'parks'),
('Galaxy''s Edge', 'parks'),
('Disneyland Park', 'parks'),
('Disney California Adventure', 'parks'),
('Tokyo Disneyland', 'parks'),
('Tokyo DisneySea', 'parks'),
('Woody', 'pixar'),
('Buzz Lightyear', 'pixar'),
('Jessie', 'pixar'),
('Bo Peep', 'pixar'),
('Slinky Dog', 'pixar'),
('Mr. Potato Head', 'pixar'),
('Mrs. Potato Head', 'pixar'),
('Alien', 'pixar'),
('Lotso', 'pixar'),
('Forky', 'pixar'),
('Duke Caboom', 'pixar'),
('Gabby Gabby', 'pixar'),
('Dolly', 'pixar'),
('Buttercup', 'pixar'),
('Mr. Pricklepants', 'pixar'),
('Trixie', 'pixar'),
('Sid Phillips', 'pixar'),
('Stinky Pete', 'pixar'),
('Emperor Zurg', 'pixar'),
('Bullseye', 'pixar'),
('Nemo', 'pixar'),
('Dory', 'pixar'),
('Marlin', 'pixar'),
('Gill', 'pixar'),
('Bruce', 'pixar'),
('Crush', 'pixar'),
('Squirt', 'pixar'),
('Mr. Ray', 'pixar'),
('Hank', 'pixar'),
('Bailey', 'pixar'),
('Destiny', 'pixar'),
('Nigel', 'pixar'),
('Jacques', 'pixar'),
('Peach', 'pixar'),
('Bloat', 'pixar'),
('Bubbles', 'pixar'),
('Deb', 'pixar'),
('Sheldon', 'pixar'),
('Darla', 'pixar'),
('P. Sherman', 'pixar'),
('Sully', 'pixar'),
('Mike Wazowski', 'pixar'),
('Boo', 'pixar'),
('Randall Boggs', 'pixar'),
('Roz', 'pixar'),
('Celia Mae', 'pixar'),
('Henry J. Waternoose', 'pixar'),
('Fungus', 'pixar'),
('Needleman and Smitty', 'pixar'),
('Abominable Snowman', 'pixar'),
('Art', 'pixar'),
('Squishy', 'pixar'),
('Don Carlton', 'pixar'),
('Terri and Terry Perry', 'pixar'),
('Scott ''Squishy'' Squibbles', 'pixar'),
('Dean Hardscrabble', 'pixar'),
('Joy', 'pixar'),
('Sadness', 'pixar'),
('Anger', 'pixar'),
('Fear', 'pixar'),
('Disgust', 'pixar'),
('Bing Bong', 'pixar'),
('Riley Andersen', 'pixar'),
('Anxiety', 'pixar'),
('Envy', 'pixar'),
('Embarrassment', 'pixar'),
('Ennui', 'pixar'),
('Nostalgia', 'pixar'),
('WALL-E', 'pixar'),
('EVE', 'pixar'),
('M-O', 'pixar'),
('Captain B. McCrea', 'pixar'),
('AUTO', 'pixar'),
('Flik', 'pixar'),
('Atta', 'pixar'),
('Dot', 'pixar'),
('Heimlich', 'pixar'),
('Slim', 'pixar'),
('Francis', 'pixar'),
('Dim', 'pixar'),
('Rosie', 'pixar'),
('P.T. Flea', 'pixar'),
('Hopper', 'pixar'),
('Molt', 'pixar'),
('Thumper', 'pixar'),
('Remy', 'pixar'),
('Alfredo Linguini', 'pixar'),
('Colette Tatou', 'pixar'),
('Auguste Gusteau', 'pixar'),
('Anton Ego', 'pixar'),
('Django', 'pixar'),
('Emile', 'pixar'),
('Skinner', 'pixar'),
('Lightning McQueen', 'pixar'),
('Tow Mater', 'pixar'),
('Doc Hudson', 'pixar'),
('Sally Carrera', 'pixar'),
('Luigi', 'pixar'),
('Guido', 'pixar'),
('Ramone', 'pixar'),
('Flo', 'pixar'),
('Sarge', 'pixar'),
('Fillmore', 'pixar'),
('Sheriff', 'pixar'),
('Red', 'pixar'),
('Chick Hicks', 'pixar'),
('The King', 'pixar'),
('Francesco Bernoulli', 'pixar'),
('Finn McMissile', 'pixar'),
('Holley Shiftwell', 'pixar'),
('Jackson Storm', 'pixar'),
('Cruz Ramirez', 'pixar'),
('Smokey', 'pixar'),
('Mr. Incredible', 'pixar'),
('Elastigirl', 'pixar'),
('Violet Parr', 'pixar'),
('Dash Parr', 'pixar'),
('Jack-Jack Parr', 'pixar'),
('Frozone', 'pixar'),
('Edna Mode', 'pixar'),
('Syndrome', 'pixar'),
('The Underminer', 'pixar'),
('Screenslaver', 'pixar'),
('Voyd', 'pixar'),
('Carl Fredricksen', 'pixar'),
('Russell', 'pixar'),
('Dug', 'pixar'),
('Kevin', 'pixar'),
('Charles Muntz', 'pixar'),
('Alpha', 'pixar'),
('Beta', 'pixar'),
('Gamma', 'pixar'),
('Joe Gardner', 'pixar'),
('22', 'pixar'),
('Terry', 'pixar'),
('Moonwind', 'pixar'),
('Dorothea Williams', 'pixar'),
('Miguel Rivera', 'pixar'),
('Hector', 'pixar'),
('Mama Imelda', 'pixar'),
('Ernesto de la Cruz', 'pixar'),
('Dante', 'pixar'),
('Pepita', 'pixar'),
('Mama Coco', 'pixar'),
('Abuelita', 'pixar'),
('Luca Paguro', 'pixar'),
('Alberto Scorfano', 'pixar'),
('Giulia Marcovaldo', 'pixar'),
('Massimo Marcovaldo', 'pixar'),
('Mei Lee', 'pixar'),
('Ming Lee', 'pixar'),
('Miriam', 'pixar'),
('Priya', 'pixar'),
('Abby', 'pixar'),
('Tyler', 'pixar'),
('4*Town', 'pixar'),
('Ember Lumen', 'pixar'),
('Wade Ripple', 'pixar'),
('Ian Lightfoot', 'pixar'),
('Barley Lightfoot', 'pixar'),
('The Manticore', 'pixar'),
('Raya', 'pixar'),
('Sisu', 'pixar'),
('Namaari', 'pixar'),
('Tuk Tuk', 'pixar'),
('Toy Story', 'pixar'),
('Toy Story 2', 'pixar'),
('Toy Story 3', 'pixar'),
('Toy Story 4', 'pixar'),
('Finding Nemo', 'pixar'),
('Finding Dory', 'pixar'),
('Monsters, Inc.', 'pixar'),
('Monsters University', 'pixar'),
('The Incredibles', 'pixar'),
('Incredibles 2', 'pixar'),
('Cars', 'pixar'),
('Cars 2', 'pixar'),
('Cars 3', 'pixar'),
('Up', 'pixar'),
('Inside Out', 'pixar'),
('Inside Out 2', 'pixar'),
('Coco', 'pixar'),
('Soul', 'pixar'),
('Luca', 'pixar'),
('Turning Red', 'pixar'),
('Elemental', 'pixar'),
('Onward', 'pixar'),
('Ratatouille', 'pixar'),
('WALL-E', 'pixar'),
('Brave', 'pixar'),
('The Good Dinosaur', 'pixar'),
('A Bug''s Life', 'pixar'),
('Lightyear', 'pixar'),
('Elio', 'pixar'),
('Space Mountain', 'rides'),
('Haunted Mansion', 'rides'),
('Pirates of the Caribbean', 'rides'),
('Big Thunder Mountain Railroad', 'rides'),
('It''s a Small World', 'rides'),
('Tower of Terror', 'rides'),
('Expedition Everest', 'rides'),
('Rock ''n'' Roller Coaster', 'rides'),
('Flight of Passage', 'rides'),
('TRON Lightcycle Run', 'rides'),
('Jungle Cruise', 'rides'),
('Splash Mountain', 'rides'),
('Seven Dwarfs Mine Train', 'rides'),
('Peter Pan''s Flight', 'rides'),
('Buzz Lightyear''s Space Ranger Spin', 'rides'),
('Tomorrowland Speedway', 'rides'),
('Astro Orbiter', 'rides'),
('Dumbo the Flying Elephant', 'rides'),
('The Magic Carpets of Aladdin', 'rides'),
('Prince Charming Regal Carrousel', 'rides'),
('The Barnstormer', 'rides'),
('Mad Tea Party', 'rides'),
('Under the Sea', 'rides'),
('The Many Adventures of Winnie the Pooh', 'rides'),
('Mickey''s PhilharMagic', 'rides'),
('Monster''s Inc. Laugh Floor', 'rides'),
('Carousel of Progress', 'rides'),
('Country Bear Jamboree', 'rides'),
('Hall of Presidents', 'rides'),
('Liberty Square Riverboat', 'rides'),
('Tom Sawyer Island', 'rides'),
('A Pirate''s Adventure', 'rides'),
('Swiss Family Treehouse', 'rides'),
('Enchanted Tales with Belle', 'rides'),
('Walt Disney World Railroad', 'rides'),
('Tiana''s Bayou Adventure', 'rides'),
('Soarin'' Around the World', 'rides'),
('Spaceship Earth', 'rides'),
('Test Track', 'rides'),
('Mission: SPACE', 'rides'),
('Living with the Land', 'rides'),
('The Seas with Nemo and Friends', 'rides'),
('Frozen Ever After', 'rides'),
('Remy''s Ratatouille Adventure', 'rides'),
('Journey of Water', 'rides'),
('Guardians of the Galaxy: Cosmic Rewind', 'rides'),
('Gran Fiesta Tour', 'rides'),
('Figment', 'rides'),
('Journey Into Imagination', 'rides'),
('Slinky Dog Dash', 'rides'),
('Alien Swirling Saucers', 'rides'),
('Toy Story Mania', 'rides'),
('Rise of the Resistance', 'rides'),
('Millennium Falcon: Smugglers Run', 'rides'),
('Mickey and Minnie''s Runaway Railway', 'rides'),
('Star Tours', 'rides'),
('Indiana Jones Adventure', 'rides'),
('Twilight Zone Tower of Terror', 'rides'),
('Kilimanjaro Safaris', 'rides'),
('Kali River Rapids', 'rides'),
('DINOSAUR', 'rides'),
('Na''vi River Journey', 'rides'),
('TriceraTop Spin', 'rides'),
('It''s Tough to Be a Bug!', 'rides'),
('Matterhorn Bobsleds', 'rides'),
('Indiana Jones Adventure', 'rides'),
('Radiator Springs Racers', 'rides'),
('Incredicoaster', 'rides'),
('Guardians of the Galaxy - Mission', 'rides'),
('Web Slingers', 'rides'),
('Grizzly River Run', 'rides'),
('Soarin'' Over California', 'rides'),
('Pixar Pal-A-Round', 'rides'),
('Toy Story Midway Mania', 'rides'),
('Luigi''s Rollickin'' Roadsters', 'rides'),
('Mater''s Junkyard Jamboree', 'rides'),
('Roger Rabbit''s Car Toon Spin', 'rides'),
('Gadget''s Go Coaster', 'rides'),
('Pirates of the Caribbean', 'rides'),
('Splash Mountain', 'rides'),
('Thunder Mountain', 'rides'),
('Star Tours: The Adventures Continue', 'rides'),
('Autopia', 'rides'),
('Finding Nemo Submarine Voyage', 'rides'),
('Storybook Land Canal Boats', 'rides'),
('King Arthur Carrousel', 'rides'),
('Casey Jr. Circus Train', 'rides'),
('Alice in Wonderland', 'rides'),
('Pinocchio''s Daring Journey', 'rides'),
('Snow White''s Enchanted Wish', 'rides'),
('Mr. Toad''s Wild Ride', 'rides'),
('Haunted Mansion Holiday', 'rides'),
('It''s a Small World Holiday', 'rides'),
('Space Mountain Ghost Galaxy', 'rides'),
('Jingle Cruise', 'rides'),
('Happily Ever After', 'rides'),
('Enchantment', 'rides'),
('EPCOT Forever', 'rides'),
('Harmonious', 'rides'),
('Luminous', 'rides'),
('Fantasmic!', 'rides'),
('World of Color', 'rides'),
('Wondrous Journeys', 'rides'),
('Festival of Fantasy Parade', 'rides'),
('Magic Happens', 'rides'),
('Disney Enchantment', 'rides'),
('Let It Go', 'songs'),
('A Whole New World', 'songs'),
('Circle of Life', 'songs'),
('Under the Sea', 'songs'),
('Part of Your World', 'songs'),
('Beauty and the Beast', 'songs'),
('Be Our Guest', 'songs'),
('Colors of the Wind', 'songs'),
('Reflection', 'songs'),
('I''ll Make a Man Out of You', 'songs'),
('A Dream Is a Wish Your Heart Makes', 'songs'),
('Bibbidi-Bobbidi-Boo', 'songs'),
('When You Wish Upon a Star', 'songs'),
('Supercalifragilisticexpialidocious', 'songs'),
('Chim Chim Cher-ee', 'songs'),
('Hakuna Matata', 'songs'),
('Can You Feel the Love Tonight', 'songs'),
('I Just Can''t Wait to Be King', 'songs'),
('Be Prepared', 'songs'),
('Friend Like Me', 'songs'),
('Prince Ali', 'songs'),
('Arabian Nights', 'songs'),
('One Jump Ahead', 'songs'),
('Kiss the Girl', 'songs'),
('Poor Unfortunate Souls', 'songs'),
('Do You Want to Build a Snowman', 'songs'),
('For the First Time in Forever', 'songs'),
('Love Is an Open Door', 'songs'),
('In Summer', 'songs'),
('Fixer Upper', 'songs'),
('Into the Unknown', 'songs'),
('Show Yourself', 'songs'),
('Some Things Never Change', 'songs'),
('Lost in the Woods', 'songs'),
('How Far I''ll Go', 'songs'),
('You''re Welcome', 'songs'),
('Shiny', 'songs'),
('Where You Are', 'songs'),
('We Know the Way', 'songs'),
('We Don''t Talk About Bruno', 'songs'),
('Surface Pressure', 'songs'),
('What Else Can I Do?', 'songs'),
('The Family Madrigal', 'songs'),
('Waiting on a Miracle', 'songs'),
('I See the Light', 'songs'),
('Mother Knows Best', 'songs'),
('When Will My Life Begin', 'songs'),
('I''ve Got a Dream', 'songs'),
('Touch the Sky', 'songs'),
('Almost There', 'songs'),
('Down in New Orleans', 'songs'),
('Dig a Little Deeper', 'songs'),
('Friends on the Other Side', 'songs'),
('Ma Belle Evangeline', 'songs'),
('Gonna Take You There', 'songs'),
('Hawaiian Roller Coaster Ride', 'songs'),
('He Mele No Lilo', 'songs'),
('You''ve Got a Friend in Me', 'songs'),
('Strange Things', 'songs'),
('I Will Go Sailing No More', 'songs'),
('When She Loved Me', 'songs'),
('We Belong Together', 'songs'),
('I Ain''t Got No Body', 'songs'),
('If I Didn''t Have You', 'songs'),
('Put That Thing Back Where It Came', 'songs'),
('Beyond the Sea', 'songs'),
('Just Keep Swimming', 'songs'),
('Remember Me', 'songs'),
('Un Poco Loco', 'songs'),
('La Llorona', 'songs'),
('Proud Corazón', 'songs'),
('It''s a Small World', 'songs'),
('Zip-A-Dee-Doo-Dah', 'songs'),
('Yo Ho Yo Ho A Pirate''s Life', 'songs'),
('Grim Grinning Ghosts', 'songs'),
('The Tiki Tiki Tiki Room', 'songs'),
('There''s a Great Big Beautiful Tomorrow', 'songs'),
('One Little Spark', 'songs'),
('Soarin'' Theme', 'songs'),
('Baroque Hoedown', 'songs'),
('The Best of Both Worlds', 'songs'),
('What Time Is It', 'songs'),
('Breaking Free', 'songs'),
('Bop to the Top', 'songs'),
('Stick to the Status Quo', 'songs'),
('Everybody Wants to Be a Cat', 'songs'),
('The Bare Necessities', 'songs'),
('I Wanna Be Like You', 'songs'),
('Trust in Me', 'songs'),
('Colonel Hathi''s March', 'songs'),
('Scales and Arpeggios', 'songs'),
('Baby Mine', 'songs'),
('Pink Elephants on Parade', 'songs'),
('Casey Junior', 'songs'),
('Little April Shower', 'songs'),
('Love Is a Song', 'songs'),
('Feed the Birds', 'songs'),
('A Spoonful of Sugar', 'songs'),
('Step in Time', 'songs'),
('Jolly Holiday', 'songs'),
('Go the Distance', 'songs'),
('Zero to Hero', 'songs'),
('I Won''t Say I''m in Love', 'songs'),
('The Gospel Truth', 'songs'),
('Oo-De-Lally', 'songs'),
('Not in Nottingham', 'songs'),
('The Phony King of England', 'songs'),
('Whistle Stop', 'songs'),
('Cruella De Vil', 'songs'),
('Candle on the Water', 'songs'),
('Once Upon a Dream', 'songs'),
('True Love''s Kiss', 'songs'),
('Heigh-Ho', 'songs'),
('Someday My Prince Will Come', 'songs'),
('Lavender Blue', 'songs'),
('A Star Is Born', 'songs'),
('Trashin'' the Camp', 'songs'),
('Strangers Like Me', 'songs'),
('You''ll Be in My Heart', 'songs'),
('Son of Man', 'songs'),
('Two Worlds', 'songs'),
('God Help the Outcasts', 'songs'),
('Out There', 'songs'),
('Topsy Turvy', 'songs'),
('Hellfire', 'songs'),
('A Guy Like You', 'songs'),
('Rotten to the Core', 'songs'),
('Ways to Be Wicked', 'songs'),
('Queen of Mean', 'songs'),
('Night Falls', 'songs'),
('Luke Skywalker', 'star_wars'),
('Darth Vader', 'star_wars'),
('Princess Leia', 'star_wars'),
('Han Solo', 'star_wars'),
('Chewbacca', 'star_wars'),
('Yoda', 'star_wars'),
('Obi-Wan Kenobi', 'star_wars'),
('Anakin Skywalker', 'star_wars'),
('Padmé Amidala', 'star_wars'),
('Emperor Palpatine', 'star_wars'),
('Darth Maul', 'star_wars'),
('Count Dooku', 'star_wars'),
('General Grievous', 'star_wars'),
('Mace Windu', 'star_wars'),
('Qui-Gon Jinn', 'star_wars'),
('Ahsoka Tano', 'star_wars'),
('Captain Rex', 'star_wars'),
('Commander Cody', 'star_wars'),
('Boba Fett', 'star_wars'),
('Jango Fett', 'star_wars'),
('Jabba the Hutt', 'star_wars'),
('Lando Calrissian', 'star_wars'),
('C-3PO', 'star_wars'),
('R2-D2', 'star_wars'),
('BB-8', 'star_wars'),
('Rey', 'star_wars'),
('Kylo Ren', 'star_wars'),
('Finn', 'star_wars'),
('Poe Dameron', 'star_wars'),
('Supreme Leader Snoke', 'star_wars'),
('General Hux', 'star_wars'),
('Rose Tico', 'star_wars'),
('Maz Kanata', 'star_wars'),
('Din Djarin', 'star_wars'),
('The Mandalorian', 'star_wars'),
('Grogu', 'star_wars'),
('Baby Yoda', 'star_wars'),
('Cara Dune', 'star_wars'),
('Greef Karga', 'star_wars'),
('Moff Gideon', 'star_wars'),
('Bo-Katan Kryze', 'star_wars'),
('The Armorer', 'star_wars'),
('Kuiil', 'star_wars'),
('IG-11', 'star_wars'),
('Fennec Shand', 'star_wars'),
('Cad Bane', 'star_wars'),
('Cassian Andor', 'star_wars'),
('Jyn Erso', 'star_wars'),
('K-2SO', 'star_wars'),
('Chirrut Îmwe', 'star_wars'),
('Baze Malbus', 'star_wars'),
('Director Krennic', 'star_wars'),
('Grand Moff Tarkin', 'star_wars'),
('Grand Admiral Thrawn', 'star_wars'),
('Ezra Bridger', 'star_wars'),
('Hera Syndulla', 'star_wars'),
('Kanan Jarrus', 'star_wars'),
('Sabine Wren', 'star_wars'),
('Chopper', 'star_wars'),
('Zeb Orrelios', 'star_wars'),
('The Inquisitor', 'star_wars'),
('Cal Kestis', 'star_wars'),
('BD-1', 'star_wars'),
('Asajj Ventress', 'star_wars'),
('Savage Opress', 'star_wars'),
('Barriss Offee', 'star_wars'),
('Luminara Unduli', 'star_wars'),
('Kit Fisto', 'star_wars'),
('Aayla Secura', 'star_wars'),
('Plo Koon', 'star_wars'),
('Ki-Adi-Mundi', 'star_wars'),
('Shaak Ti', 'star_wars'),
('Nute Gunray', 'star_wars'),
('Jar Jar Binks', 'star_wars'),
('Watto', 'star_wars'),
('Sebulba', 'star_wars'),
('Tatooine', 'star_wars'),
('Coruscant', 'star_wars'),
('Naboo', 'star_wars'),
('Hoth', 'star_wars'),
('Endor', 'star_wars'),
('Dagobah', 'star_wars'),
('Bespin', 'star_wars'),
('Cloud City', 'star_wars'),
('Mustafar', 'star_wars'),
('Kamino', 'star_wars'),
('Geonosis', 'star_wars'),
('Kashyyyk', 'star_wars'),
('Mandalore', 'star_wars'),
('Jakku', 'star_wars'),
('Takodana', 'star_wars'),
('Starkiller Base', 'star_wars'),
('Exegol', 'star_wars'),
('Scarif', 'star_wars'),
('Jedha', 'star_wars'),
('Lothal', 'star_wars'),
('Dathomir', 'star_wars'),
('Nevarro', 'star_wars'),
('Arvala-7', 'star_wars'),
('Millennium Falcon', 'star_wars'),
('X-Wing', 'star_wars'),
('TIE Fighter', 'star_wars'),
('Star Destroyer', 'star_wars'),
('Death Star', 'star_wars'),
('Death Star II', 'star_wars'),
('AT-AT', 'star_wars'),
('AT-ST', 'star_wars'),
('Slave I', 'star_wars'),
('Razor Crest', 'star_wars'),
('Jedi Starfighter', 'star_wars'),
('A-Wing', 'star_wars'),
('B-Wing', 'star_wars'),
('Y-Wing', 'star_wars'),
('Naboo Starfighter', 'star_wars'),
('Podracer', 'star_wars'),
('Speeder Bike', 'star_wars'),
('Landspeeder', 'star_wars'),
('Sandcrawler', 'star_wars'),
('The Ghost', 'star_wars'),
('Super Star Destroyer', 'star_wars'),
('Republic Cruiser', 'star_wars'),
('Droid Control Ship', 'star_wars'),
('Trade Federation Battleship', 'star_wars'),
('Interceptor', 'star_wars'),
('Jedi', 'star_wars'),
('Sith', 'star_wars'),
('The Force', 'star_wars'),
('Lightsaber', 'star_wars'),
('Dark Side', 'star_wars'),
('Light Side', 'star_wars'),
('Galactic Empire', 'star_wars'),
('Rebel Alliance', 'star_wars'),
('The Resistance', 'star_wars'),
('First Order', 'star_wars'),
('Galactic Republic', 'star_wars'),
('Separatists', 'star_wars'),
('Clone Troopers', 'star_wars'),
('Stormtroopers', 'star_wars'),
('Wookiee', 'star_wars'),
('Ewok', 'star_wars'),
('Tusken Raiders', 'star_wars'),
('Jawas', 'star_wars'),
('Sarlacc', 'star_wars'),
('Rancor', 'star_wars'),
('Krayt Dragon', 'star_wars'),
('Blurrg', 'star_wars'),
('Bantha', 'star_wars'),
('Tauntaun', 'star_wars'),
('Wampa', 'star_wars'),
('Mynock', 'star_wars'),
('Space Slug', 'star_wars'),
('Porg', 'star_wars'),
('Loth-Cat', 'star_wars'),
('Loth-Wolf', 'star_wars'),
('Convor', 'star_wars'),
('Vulptex', 'star_wars'),
('Order 66', 'star_wars'),
('Kyber Crystal', 'star_wars'),
('Holocron', 'star_wars'),
('Darksaber', 'star_wars'),
('Beskar', 'star_wars'),
('Carbonite', 'star_wars'),
('Bacta Tank', 'star_wars'),
('Hyperspace', 'star_wars'),
('Cantina Band', 'star_wars'),
('Mos Eisley Cantina', 'star_wars'),
('Dex''s Diner', 'star_wars'),
('Jedi Temple', 'star_wars'),
('Jedi Council', 'star_wars'),
('Bounty Hunter', 'star_wars'),
('Mandalorian Creed', 'star_wars'),
('This Is the Way', 'star_wars'),
('May the Force Be with You', 'star_wars'),
('I Have a Bad Feeling About This', 'star_wars'),
('Do or Do Not There Is No Try', 'star_wars'),
('DuckTales', 'shows'),
('Kim Possible', 'shows'),
('Phineas and Ferb', 'shows'),
('Gravity Falls', 'shows'),
('The Owl House', 'shows'),
('Amphibia', 'shows'),
('The Ghost and Molly McGee', 'shows'),
('Big City Greens', 'shows'),
('Bluey', 'shows'),
('Hannah Montana', 'shows'),
('Wizards of Waverly Place', 'shows'),
('Suite Life of Zack and Cody', 'shows'),
('That''s So Raven', 'shows'),
('Jessie', 'shows'),
('Good Luck Charlie', 'shows'),
('Liv and Maddie', 'shows'),
('K.C. Undercover', 'shows'),
('Austin & Ally', 'shows'),
('A.N.T. Farm', 'shows'),
('Shake It Up', 'shows'),
('Sonny with a Chance', 'shows'),
('Jonas', 'shows'),
('The Proud Family', 'shows'),
('Recess', 'shows'),
('Gargoyles', 'shows'),
('TaleSpin', 'shows'),
('Chip ''n Dale Rescue Rangers', 'shows'),
('Goof Troop', 'shows'),
('Darkwing Duck', 'shows'),
('Bonkers', 'shows'),
('The Weekenders', 'shows'),
('Fillmore!', 'shows'),
('Lloyd in Space', 'shows'),
('Pepper Ann', 'shows'),
('Buzz Lightyear of Star Command', 'shows'),
('Hercules: The Series', 'shows'),
('Aladdin: The Series', 'shows'),
('The Little Mermaid: The Series', 'shows'),
('Timon and Pumbaa', 'shows'),
('101 Dalmatians: The Series', 'shows'),
('Lilo and Stitch: The Series', 'shows'),
('Jake and the Never Land Pirates', 'shows'),
('Sofia the First', 'shows'),
('Elena of Avalor', 'shows'),
('Doc McStuffins', 'shows'),
('The Lion Guard', 'shows'),
('Tangled: The Series', 'shows'),
('Star vs. the Forces of Evil', 'shows'),
('Wander Over Yonder', 'shows'),
('Star Wars: The Clone Wars', 'shows'),
('Star Wars Rebels', 'shows'),
('The Bad Batch', 'shows'),
('Ahsoka', 'shows'),
('Andor', 'shows'),
('The Book of Boba Fett', 'shows'),
('Obi-Wan Kenobi', 'shows'),
('WandaVision', 'shows'),
('Loki', 'shows'),
('The Falcon and the Winter Soldier', 'shows'),
('Moon Knight', 'shows'),
('She-Hulk', 'shows'),
('Ms. Marvel', 'shows'),
('Hawkeye', 'shows'),
('Secret Invasion', 'shows'),
('High School Musical', 'shows'),
('Descendants', 'shows'),
('Zombies', 'shows'),
('Teen Beach Movie', 'shows'),
('Camp Rock', 'shows'),
('Newsies', 'shows'),
('The Cheetah Girls', 'shows'),
('Jump In!', 'shows'),
('Cadet Kelly', 'shows'),
('Zenon: Girl of the 21st Century', 'shows'),
('Smart House', 'shows'),
('Halloweentown', 'shows'),
('Twitches', 'shows'),
('Starstruck', 'shows'),
('Lemonade Mouth', 'shows'),
('Let It Shine', 'shows'),
('Cloud 9', 'shows'),
('Adventures in Babysitting', 'shows'),
('Disney Afternoon', 'shows'),
('One Saturday Morning', 'shows'),
('Toon Disney', 'shows'),
('Playhouse Disney', 'shows'),
('Disney Junior', 'shows'),
('Disney XD', 'shows'),
('Mickey Mouse Clubhouse', 'shows'),
('Mickey Mouse Funhouse', 'shows'),
('Bear in the Big Blue House', 'shows'),
('Out of the Box', 'shows'),
('Rolie Polie Olie', 'shows'),
('PB&J Otter', 'shows'),
('Madeline', 'shows'),
('Little Einsteins', 'shows'),
('Imagination Movers', 'shows'),
('Handy Manny', 'shows'),
('Special Agent Oso', 'shows'),
('Vampirina', 'shows'),
('T.O.T.S.', 'shows'),
('The Wonderful World of Mickey Mouse', 'shows'),
('Maleficent', 'villains'),
('Ursula', 'villains'),
('Cruella De Vil', 'villains'),
('Jafar', 'villains'),
('Scar', 'villains'),
('Gaston', 'villains'),
('Hades', 'villains'),
('Captain Hook', 'villains'),
('Evil Queen', 'villains'),
('Lady Tremaine', 'villains'),
('Mother Gothel', 'villains'),
('Dr. Facilier', 'villains'),
('Hans', 'villains'),
('Shan Yu', 'villains'),
('Frollo', 'villains'),
('Governor Ratcliffe', 'villains'),
('Queen of Hearts', 'villains'),
('Madame Medusa', 'villains'),
('Prince John', 'villains'),
('Sheriff of Nottingham', 'villains'),
('Stromboli', 'villains'),
('The Coachman', 'villains'),
('Honest John and Gideon', 'villains'),
('Chernabog', 'villains'),
('Headless Horseman', 'villains'),
('Captain Gantu', 'villains'),
('Dr. Hamsterviel', 'villains'),
('Yzma', 'villains'),
('Kronk', 'villains'),
('Syndrome', 'villains'),
('Lots-o''-Huggin'' Bear', 'villains'),
('Randall Boggs', 'villains'),
('Henry J. Waternoose III', 'villains'),
('Hopper', 'villains'),
('Ernesto de la Cruz', 'villains'),
('Charles Muntz', 'villains'),
('Stinky Pete', 'villains'),
('Zurg', 'villains'),
('Sid Phillips', 'villains'),
('AUTO', 'villains'),
('Screenslaver', 'villains'),
('Darth Vader', 'villains'),
('Emperor Palpatine', 'villains'),
('Darth Maul', 'villains'),
('Kylo Ren', 'villains'),
('Grand Moff Tarkin', 'villains'),
('Count Dooku', 'villains'),
('General Grievous', 'villains'),
('Jabba the Hutt', 'villains'),
('Boba Fett', 'villains'),
('Grand Admiral Thrawn', 'villains'),
('Asajj Ventress', 'villains'),
('The Inquisitor', 'villains'),
('Moff Gideon', 'villains'),
('Snoke', 'villains'),
('General Hux', 'villains'),
('Director Krennic', 'villains'),
('Cad Bane', 'villains'),
('Savage Opress', 'villains'),
('Pre Vizsla', 'villains'),
('Nute Gunray', 'villains'),
('Sebulba', 'villains'),
('Watto', 'villains'),
('Aurra Sing', 'villains'),
('Embo', 'villains'),
('Dengar', 'villains'),
('Bossk', 'villains'),
('IG-88', 'villains'),
('4-LOM', 'villains'),
('Zuckuss', 'villains'),
('Thanos', 'villains'),
('Loki', 'villains'),
('Ultron', 'villains'),
('Hela', 'villains'),
('Killmonger', 'villains'),
('Kang the Conqueror', 'villains'),
('Green Goblin', 'villains'),
('Doctor Octopus', 'villains'),
('Vulture', 'villains'),
('Mysterio', 'villains'),
('Kingpin', 'villains'),
('Red Skull', 'villains'),
('Helmut Zemo', 'villains'),
('Crossbones', 'villains'),
('Wenwu', 'villains'),
('Gorr the God Butcher', 'villains'),
('Namor', 'villains'),
('The High Evolutionary', 'villains'),
('Ronan the Accuser', 'villains'),
('Ego', 'villains'),
('Dormammu', 'villains'),
('Kaecilius', 'villains'),
('Obadiah Stane', 'villains'),
('Aldrich Killian', 'villains'),
('Whiplash', 'villains'),
('Abomination', 'villains'),
('Xu Wenwu', 'villains'),
('Agatha Harkness', 'villains'),
('He Who Remains', 'villains'),
('Wanda Maximoff', 'villains'),
('Dreykov', 'villains'),
('Taskmaster', 'villains'),
('Gorilla Grodd', 'villains'),
('Darren Cross', 'villains'),
('Ghost', 'villains'),
('General Ross', 'villains'),
('Prowler', 'villains'),
('The Leader', 'villains'),
('Galactus', 'villains'),
('Doctor Doom', 'villains'),
('Magneto', 'villains'),
('Apocalypse', 'villains'),
('Mr. Sinister', 'villains'),
('Sentinels', 'villains'),
('Dark Phoenix', 'villains'),
('Mystique', 'villains'),
('Sabretooth', 'villains'),
('Juggernaut', 'villains'),
('Lady Deathstrike', 'villains'),
('William Stryker', 'villains'),
('Sebastian Shaw', 'villains'),
('Emma Frost', 'villains'),
('Toad', 'villains'),
('Pyro', 'villains'),
('Avalanche', 'villains'),
('Blob', 'villains'),
('Madame Mim', 'villains'),
('Shere Khan', 'villains'),
('Kaa', 'villains'),
('King Candy', 'villains'),
('Turbo', 'villains'),
('Tamatoa', 'villains'),
('Te Ka', 'villains'),
('Yokai', 'villains'),
('Bellwether', 'villains'),
('Duke of Weselton', 'villains'),
('King Runeard', 'villains'),
('Namaari', 'villains'),
('Druun', 'villains'),
('Skinner', 'villains'),
('Anton Ego', 'villains'),
('Jackson Storm', 'villains'),
('Chick Hicks', 'villains'),
('The Underminer', 'villains'),
('Mor''du', 'villains'),
('Alameda Slim', 'villains'),
('Clayton', 'villains'),
('McLeach', 'villains'),
('Edgar Balthazar', 'villains'),
('Davy Jones', 'villains'),
('Hector Barbossa', 'villains'),
('Cutler Beckett', 'villains'),
('Blackbeard', 'villains'),
('Captain Salazar', 'villains'),
('Commander Rourke', 'villains'),
('Helga Sinclair', 'villains'),
('Oogie Boogie', 'villains'),
('Bowler Hat Guy', 'villains'),
('DOR-15', 'villains'),
('Dawn Bellwether', 'villains'),
('Thunderclap', 'villains'),
('Butkus', 'villains'),
('Scroop', 'villains'),
('Horned King', 'villains'),
('Cauldron Born', 'villains');